apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    tier: data
    role: database
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: data
      role: database
  template:
    metadata:
      labels:
        tier: data
        role: database
    spec:
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
      containers:
      - name: mongo-db
        image: mongo:3.6.2
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      - name: redis
        image: redis:4.0.8-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    tier: network
    role: lb-db
spec:
  ports:
  - name: mongo-db
    port: 27017
    targetPort: 27017
  - name: redis
    port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    tier: data
    role: database