apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    tier: persistent
    role: database
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mongo-pv/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      tier: persistent
      role: database